-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               5.5.28a-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL version:             7.0.0.4053
-- Date/time:                    2015-03-27 21:31:11
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

-- Dumping database structure for hrms
DROP DATABASE IF EXISTS `hrms`;
CREATE DATABASE IF NOT EXISTS `hrms` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `hrms`;


-- Dumping structure for table hrms.countries
DROP TABLE IF EXISTS `countries`;
CREATE TABLE IF NOT EXISTS `countries` (
  `code` char(2) CHARACTER SET latin1 NOT NULL,
  `countries_val` varchar(50) DEFAULT NULL,
  `name_fr` tinytext CHARACTER SET latin1,
  `countries_id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`countries_id`)
) ENGINE=InnoDB AUTO_INCREMENT=250 DEFAULT CHARSET=utf8;

-- Dumping data for table hrms.countries: ~248 rows (approximately)
/*!40000 ALTER TABLE `countries` DISABLE KEYS */;
INSERT INTO `countries` (`code`, `countries_val`, `name_fr`, `countries_id`) VALUES
	('AD', 'Andorra', 'Andorre', 1),
	('AE', 'United Arab Emirates', 'Émirats arabes unis', 2),
	('AF', 'Afghanistan', 'Afghanistan', 3),
	('AG', 'Antigua and Barbuda', 'Antigua-et-Barbuda', 4),
	('AI', 'Anguilla', 'Anguilla', 5),
	('AL', 'Albania', 'Albanie', 6),
	('AM', 'Armenia', 'Arménie', 7),
	('AO', 'Angola', 'Angola', 8),
	('AQ', 'Antarctica', 'Antarctique', 9),
	('AR', 'Argentina', 'Argentine', 10),
	('AS', 'American Samoa', 'Samoa américaine', 11),
	('AT', 'Austria', 'Autriche', 12),
	('AU', 'Australia', 'Australie', 13),
	('AW', 'Aruba', 'Aruba', 14),
	('AX', 'Aland Islands', 'Îles d\'Åland', 15),
	('AZ', 'Azerbaijan', 'Azerbaïdjan', 16),
	('BA', 'Bosnia and Herzegovina', 'Bosnie-Herzégovine', 17),
	('BB', 'Barbados', 'Barbade', 18),
	('BD', 'Bangladesh', 'Bangladesh', 19),
	('BE', 'Belgium', 'Belgique', 20),
	('BF', 'Burkina Faso', 'Burkina Faso', 21),
	('BG', 'Bulgaria', 'Bulgarie', 22),
	('BH', 'Bahrain', 'Bahreïn', 23),
	('BI', 'Burundi', 'Burundi', 24),
	('BJ', 'Benin', 'Bénin', 25),
	('BL', 'Saint BarthÃ©lemy', 'Saint-Barthélemy', 26),
	('BM', 'Bermuda', 'Bermudes', 27),
	('BN', 'Brunei Darussalam', 'Brunei Darussalam', 28),
	('BO', 'Bolivia', 'Bolivie', 29),
	('BQ', 'Caribbean Netherlands ', 'Pays-Bas caribéens', 30),
	('BR', 'Brazil', 'Brésil', 31),
	('BS', 'Bahamas', 'Bahamas', 32),
	('BT', 'Bhutan', 'Bhoutan', 33),
	('BV', 'Bouvet Island', 'Île Bouvet', 34),
	('BW', 'Botswana', 'Botswana', 35),
	('BY', 'Belarus', 'Bélarus', 36),
	('BZ', 'Belize', 'Belize', 37),
	('CA', 'Canada', 'Canada', 38),
	('CC', 'Cocos (Keeling) Islands', 'Îles Cocos (Keeling)', 39),
	('CD', 'Congo, Democratic Republic of', 'Congo, République démocratique du', 40),
	('CF', 'Central African Republic', 'République centrafricaine', 41),
	('CG', 'Congo', 'Congo', 42),
	('CH', 'Switzerland', 'Suisse', 43),
	('CI', 'Cote d\'Ivoire', 'Côte d\'Ivoire', 44),
	('CK', 'Cook Islands', 'Îles Cook', 45),
	('CL', 'Chile', 'Chili', 46),
	('CM', 'Cameroon', 'Cameroun', 47),
	('CN', 'China', 'Chine', 48),
	('CO', 'Colombia', 'Colombie', 49),
	('CR', 'Costa Rica', 'Costa Rica', 50),
	('CU', 'Cuba', 'Cuba', 51),
	('CV', 'Cape Verde', 'Cap-Vert', 52),
	('CW', 'Curaçao', 'Curaçao', 53),
	('CX', 'Christmas Island', 'Île Christmas', 54),
	('CY', 'Cyprus', 'Chypre', 55),
	('CZ', 'Czech Republic', 'République tchèque', 56),
	('DE', 'Germany', 'Allemagne', 57),
	('DJ', 'Djibouti', 'Djibouti', 58),
	('DK', 'Denmark', 'Danemark', 59),
	('DM', 'Dominica', 'Dominique', 60),
	('DO', 'Dominican Republic', 'République dominicaine', 61),
	('DZ', 'Algeria', 'Algérie', 62),
	('EC', 'Ecuador', 'Équateur', 63),
	('EE', 'Estonia', 'Estonie', 64),
	('EG', 'Egypt', 'Égypte', 65),
	('EH', 'Western Sahara', 'Sahara Occidental', 66),
	('ER', 'Eritrea', 'Érythrée', 67),
	('ES', 'Spain', 'Espagne', 68),
	('ET', 'Ethiopia', 'Éthiopie', 69),
	('FI', 'Finland', 'Finlande', 70),
	('FJ', 'Fiji', 'Fidji', 71),
	('FK', 'Falkland Islands', 'Îles Malouines', 72),
	('FM', 'Micronesia, Federated States of', 'Micronésie, États fédérés de', 73),
	('FO', 'Faroe Islands', 'Îles Féroé', 74),
	('FR', 'France', 'France', 75),
	('GA', 'Gabon', 'Gabon', 76),
	('GB', 'United Kingdom', 'Royaume-Uni', 77),
	('GD', 'Grenada', 'Grenade', 78),
	('GE', 'Georgia', 'Géorgie', 79),
	('GF', 'French Guiana', 'Guyane française', 80),
	('GG', 'Guernsey', 'Guernesey', 81),
	('GH', 'Ghana', 'Ghana', 82),
	('GI', 'Gibraltar', 'Gibraltar', 83),
	('GL', 'Greenland', 'Groenland', 84),
	('GM', 'Gambia', 'Gambie', 85),
	('GN', 'Guinea', 'Guinée', 86),
	('GP', 'Guadeloupe', 'Guadeloupe', 87),
	('GQ', 'Equatorial Guinea', 'Guinée équatoriale', 88),
	('GR', 'Greece', 'Grèce', 89),
	('GS', 'South Georgia and the South Sandwich Islands', 'Géorgie du Sud et les îles Sandwich du Sud', 90),
	('GT', 'Guatemala', 'Guatemala', 91),
	('GU', 'Guam', 'Guam', 92),
	('GW', 'Guinea-Bissau', 'Guinée-Bissau', 93),
	('GY', 'Guyana', 'Guyana', 94),
	('HK', 'Hong Kong', 'Hong Kong', 95),
	('HM', 'Heard and McDonald Islands', 'Îles Heard et McDonald', 96),
	('HN', 'Honduras', 'Honduras', 97),
	('HR', 'Croatia', 'Croatie', 98),
	('HT', 'Haiti', 'Haïti', 99),
	('HU', 'Hungary', 'Hongrie', 100),
	('ID', 'Indonesia', 'Indonésie', 101),
	('IE', 'Ireland', 'Irlande', 102),
	('IL', 'Israel', 'Israël', 103),
	('IM', 'Isle of Man', 'Île de Man', 104),
	('IN', 'India', 'Inde', 105),
	('IO', 'British Indian Ocean Territory', 'Territoire britannique de l\'océan Indien', 106),
	('IQ', 'Iraq', 'Irak', 107),
	('IR', 'Iran', 'Iran', 108),
	('IS', 'Iceland', 'Islande', 109),
	('IT', 'Italy', 'Italie', 110),
	('JE', 'Jersey', 'Jersey', 111),
	('JM', 'Jamaica', 'Jamaïque', 112),
	('JO', 'Jordan', 'Jordanie', 113),
	('JP', 'Japan', 'Japon', 114),
	('KE', 'Kenya', 'Kenya', 115),
	('KG', 'Kyrgyzstan', 'Kirghizistan', 116),
	('KH', 'Cambodia', 'Cambodge', 117),
	('KI', 'Kiribati', 'Kiribati', 118),
	('KM', 'Comoros', 'Comores', 119),
	('KN', 'Saint Kitts and Nevis', 'Saint-Kitts-et-Nevis', 120),
	('KP', 'North Korea', 'Corée du Nord', 121),
	('KR', 'South Korea', 'Corée du Sud', 122),
	('KW', 'Kuwait', 'Koweït', 123),
	('KY', 'Cayman Islands', 'Îles Caïmans', 124),
	('KZ', 'Kazakhstan', 'Kazakhstan', 125),
	('LA', 'Laos', 'Laos', 126),
	('LB', 'Lebanon', 'Liban', 127),
	('LC', 'Saint Lucia', 'Sainte-Lucie', 128),
	('LI', 'Liechtenstein', 'Liechtenstein', 129),
	('LK', 'Sri Lanka', 'Sri Lanka', 130),
	('LR', 'Liberia', 'Libéria', 131),
	('LS', 'Lesotho', 'Lesotho', 132),
	('LT', 'Lithuania', 'Lituanie', 133),
	('LU', 'Luxembourg', 'Luxembourg', 134),
	('LV', 'Latvia', 'Lettonie', 135),
	('LY', 'Libya', 'Libye', 136),
	('MA', 'Morocco', 'Maroc', 137),
	('MC', 'Monaco', 'Monaco', 138),
	('MD', 'Moldova', 'Moldavie', 139),
	('ME', 'Montenegro', 'Monténégro', 140),
	('MF', 'Saint-Martin (France)', 'Saint-Martin (France)', 141),
	('MG', 'Madagascar', 'Madagascar', 142),
	('MH', 'Marshall Islands', 'Îles Marshall', 143),
	('MK', 'Macedonia', 'Macédoine', 144),
	('ML', 'Mali', 'Mali', 145),
	('MM', 'Myanmar', 'Myanmar', 146),
	('MN', 'Mongolia', 'Mongolie', 147),
	('MO', 'Macau', 'Macao', 148),
	('MP', 'Northern Mariana Islands', 'Mariannes du Nord', 149),
	('MQ', 'Martinique', 'Martinique', 150),
	('MR', 'Mauritania', 'Mauritanie', 151),
	('MS', 'Montserrat', 'Montserrat', 152),
	('MT', 'Malta', 'Malte', 153),
	('MU', 'Mauritius', 'Maurice', 154),
	('MV', 'Maldives', 'Maldives', 155),
	('MW', 'Malawi', 'Malawi', 156),
	('MX', 'Mexico', 'Mexique', 157),
	('MY', 'Malaysia', 'Malaisie', 158),
	('MZ', 'Mozambique', 'Mozambique', 159),
	('NA', 'Namibia', 'Namibie', 160),
	('NC', 'New Caledonia', 'Nouvelle-Calédonie', 161),
	('NE', 'Niger', 'Niger', 162),
	('NF', 'Norfolk Island', 'Île Norfolk', 163),
	('NG', 'Nigeria', 'Nigeria', 164),
	('NI', 'Nicaragua', 'Nicaragua', 165),
	('NL', 'The Netherlands', 'Pays-Bas', 166),
	('NO', 'Norway', 'Norvège', 167),
	('NP', 'Nepal', 'Népal', 168),
	('NR', 'Nauru', 'Nauru', 169),
	('NU', 'Niue', 'Niue', 170),
	('NZ', 'New Zealand', 'Nouvelle-Zélande', 171),
	('OM', 'Oman', 'Oman', 172),
	('PA', 'Panama', 'Panama', 173),
	('PE', 'Peru', 'Pérou', 174),
	('PF', 'French Polynesia', 'Polynésie française', 175),
	('PG', 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée', 176),
	('PH', 'Philippines', 'Philippines', 177),
	('PK', 'Pakistan', 'Pakistan', 178),
	('PL', 'Poland', 'Pologne', 179),
	('PM', 'St. Pierre and Miquelon', 'Saint-Pierre-et-Miquelon', 180),
	('PN', 'Pitcairn', 'Pitcairn', 181),
	('PR', 'Puerto Rico', 'Puerto Rico', 182),
	('PS', 'Palestine, State of', 'Palestine', 183),
	('PT', 'Portugal', 'Portugal', 184),
	('PW', 'Palau', 'Palau', 185),
	('PY', 'Paraguay', 'Paraguay', 186),
	('QA', 'Qatar', 'Qatar', 187),
	('RO', 'Romania', 'Roumanie', 189),
	('RS', 'Serbia', 'Serbie', 190),
	('RU', 'Russian Federation', 'Russie', 191),
	('RW', 'Rwanda', 'Rwanda', 192),
	('SA', 'Saudi Arabia', 'Arabie saoudite', 193),
	('SB', 'Solomon Islands', 'Îles Salomon', 194),
	('SC', 'Seychelles', 'Seychelles', 195),
	('SD', 'Sudan', 'Soudan', 196),
	('SE', 'Sweden', 'Suède', 197),
	('SG', 'Singapore', 'Singapour', 198),
	('SH', 'Saint Helena', 'Sainte-Hélène', 199),
	('SI', 'Slovenia', 'Slovénie', 200),
	('SJ', 'Svalbard and Jan Mayen Islands', 'Svalbard et île de Jan Mayen', 201),
	('SK', 'Slovakia', 'Slovaquie', 202),
	('SL', 'Sierra Leone', 'Sierra Leone', 203),
	('SM', 'San Marino', 'Saint-Marin', 204),
	('SN', 'Senegal', 'Sénégal', 205),
	('SO', 'Somalia', 'Somalie', 206),
	('SR', 'Suriname', 'Suriname', 207),
	('SS', 'South Sudan', 'Soudan du Sud', 208),
	('ST', 'Sao Tome and Principe', 'Sao Tomé-et-Principe', 209),
	('SV', 'El Salvador', 'El Salvador', 210),
	('SX', 'Sint Maarten (Dutch part)', 'Saint-Martin (Pays-Bas)', 211),
	('SY', 'Syria', 'Syrie', 212),
	('SZ', 'Swaziland', 'Swaziland', 213),
	('TC', 'Turks and Caicos Islands', 'Îles Turks et Caicos', 214),
	('TD', 'Chad', 'Tchad', 215),
	('TF', 'French Southern Territories', 'Terres australes françaises', 216),
	('TG', 'Togo', 'Togo', 217),
	('TH', 'Thailand', 'Thaïlande', 218),
	('TJ', 'Tajikistan', 'Tadjikistan', 219),
	('TK', 'Tokelau', 'Tokelau', 220),
	('TL', 'Timor-Leste', 'Timor-Leste', 221),
	('TM', 'Turkmenistan', 'Turkménistan', 222),
	('TN', 'Tunisia', 'Tunisie', 223),
	('TO', 'Tonga', 'Tonga', 224),
	('TR', 'Turkey', 'Turquie', 225),
	('TT', 'Trinidad and Tobago', 'Trinité-et-Tobago', 226),
	('TV', 'Tuvalu', 'Tuvalu', 227),
	('TW', 'Taiwan', 'Taïwan', 228),
	('TZ', 'Tanzania', 'Tanzanie', 229),
	('UA', 'Ukraine', 'Ukraine', 230),
	('UG', 'Uganda', 'Ouganda', 231),
	('UM', 'United States Minor Outlying Islands', 'Îles mineures éloignées des États-Unis', 232),
	('US', 'United States', 'États-Unis', 233),
	('UY', 'Uruguay', 'Uruguay', 234),
	('UZ', 'Uzbekistan', 'Ouzbékistan', 235),
	('VA', 'Vatican', 'Vatican', 236),
	('VC', 'Saint Vincent and the Grenadines', 'Saint-Vincent-et-les-Grenadines', 237),
	('VE', 'Venezuela', 'Venezuela', 238),
	('VG', 'Virgin Islands (British)', 'Îles Vierges britanniques', 239),
	('VI', 'Virgin Islands (U.S.)', 'Îles Vierges américaines', 240),
	('VN', 'Vietnam', 'Vietnam', 241),
	('VU', 'Vanuatu', 'Vanuatu', 242),
	('WF', 'Wallis and Futuna Islands', 'Îles Wallis-et-Futuna', 243),
	('WS', 'Samoa', 'Samoa', 244),
	('YE', 'Yemen', 'Yémen', 245),
	('YT', 'Mayotte', 'Mayotte', 246),
	('ZA', 'South Africa', 'Afrique du Sud', 247),
	('ZM', 'Zambia', 'Zambie', 248),
	('ZW', 'Zimbabwe', 'Zimbabwe', 249);
/*!40000 ALTER TABLE `countries` ENABLE KEYS */;
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
