alter table employee_outpatient add paid_status int, remarks varchar(200);
alter table employee_pregnancy add paid_status int, remarks varchar(200);
alter table employee_eyeglasses add paid_status int, remarks varchar(200);
alter table employee_medical_checkup add paid_status int, remarks varchar(200);
create table signature(signature_id int auto_increment primary key, signature varchar(1000));
insert into signature(signature) values('test');
insert into email_setup(email_type, email_type_name) values('contract_reminder_employee','Contract Reminder Employee');
insert into email_setup(email_type, email_type_name) values('contract_reminder_team_leader','Contract Reminder Team Leader');
alter table employee add title varchar(30);
alter table applicants add title varchar(30);
create table title(title_id int auto_increment primary key, title varchar(30), sort_id int);
alter table applicants_reference add title varchar(30);
alter table applicants_other_reference add title varchar(30);
alter table vacancy_timeline drop column interview_date, drop column interview_time, drop column interview_place;
alter table applicants_education change column country countries_id int;
ALTER TABLE `email_setup` CHANGE COLUMN `email_subject` `email_subject` VARCHAR(100);
